export const WeaponTypes = {
  GRENADE: "weapon:grenade",
  SMOKE_GRENADE: "weapon:smoke_grenade",
  CONFETTI_CANNON: "weapon:confetti_cannon",
  STINK_BOMB: "weapon:stink_bomb",
  BANANA_BOMB: "weapon:banana_bomb",
  PARTY_ROCKET: "weapon:party_rocket",
  BAZOOKA: "weapon:bazooka",
  SLIME_BOMB: "weapon:slime_bomb",
  TOILET_PAPER: "weapon:toilet_paper",
  RUBBER_CHICKEN: "weapon:rubber_chicken",
  DISCO_GLOBE: "weapon:disco_globe",
};

export const WEAPONS = [
  {
    itemType: WeaponTypes.GRENADE,
    label: "Grenade",
    description: "Lance-la par-dessus les obstacles pour faire exploser les ennemis proches.",
    hint: "Clic gauche pour lancer une grenade explosive.",
    damage: 7,
    splashRadius: 44,
    speed: 250,
    gravity: 1250,
    fuseMs: 1000,
    cooldownMs: 650,
    color: "#f1c54b",
  },
  {
    itemType: WeaponTypes.SMOKE_GRENADE,
    label: "Fumigène",
    description: "Crée un nuage de fumée pour disparaître aux yeux des autres.",
    hint: "Clic gauche pour lancer un fumigène.",
    damage: 0,
    splashRadius: 0,
    speed: 230,
    gravity: 900,
    fuseMs: 900,
    cooldownMs: 700,
    color: "rgba(180,180,190,0.9)",
    effect: "smoke",
  },
  {
    itemType: WeaponTypes.CONFETTI_CANNON,
    label: "Canon à confettis",
    description: "Projette une pluie de confettis multicolores sans dégâts.",
    hint: "Clic gauche pour faire exploser des confettis.",
    damage: 0,
    splashRadius: 0,
    speed: 240,
    gravity: 920,
    fuseMs: 850,
    cooldownMs: 550,
    color: "#ff8ad8",
    effect: "confetti",
    destructive: false,
  },
  {
    itemType: WeaponTypes.STINK_BOMB,
    label: "Bombe puante",
    description: "Remplit la zone d'une fumée verte très douteuse.",
    hint: "Clic gauche pour lancer une bombe puante.",
    damage: 0,
    splashRadius: 0,
    speed: 220,
    gravity: 900,
    fuseMs: 900,
    cooldownMs: 650,
    color: "rgba(124, 199, 96, 0.9)",
    effect: "stink",
    destructive: false,
  },
  {
    itemType: WeaponTypes.BANANA_BOMB,
    label: "Bombe banane",
    description: "Fait un boom jaune très ridicule.",
    hint: "Clic gauche pour jeter une banane explosive.",
    damage: 4,
    splashRadius: 36,
    speed: 260,
    gravity: 980,
    fuseMs: 650,
    cooldownMs: 700,
    color: "#ffe85a",
    effect: "banana",
    destructive: true,
  },
  {
    itemType: WeaponTypes.PARTY_ROCKET,
    label: "Roquette de fête",
    description: "Lance une fusée qui éclate en festival de lumière.",
    hint: "Clic gauche pour lancer une roquette de fête.",
    damage: 0,
    splashRadius: 0,
    speed: 380,
    gravity: 760,
    fuseMs: 0,
    cooldownMs: 800,
    color: "#8b7bff",
    effect: "party",
    destructive: false,
  },
  {
    itemType: WeaponTypes.BAZOOKA,
    label: "Bazooka",
    description: "Tire une roquette qui explose à l'impact.",
    hint: "Clic gauche pour lancer une roquette.",
    damage: 10,
    splashRadius: 58,
    speed: 400,
    gravity: 760,
    fuseMs: 0,
    cooldownMs: 850,
    color: "#ff8b3d",
  },
  {
    itemType: WeaponTypes.SLIME_BOMB,
    label: "Bombe slime",
    description: "Imbibe la zone d'une gelée verte collante et ridicule.",
    hint: "Clic gauche pour lancer une boule de slime.",
    damage: 0,
    splashRadius: 0,
    speed: 235,
    gravity: 860,
    fuseMs: 800,
    cooldownMs: 600,
    color: "#6ee56a",
    effect: "slime",
    destructive: false,
  },
  {
    itemType: WeaponTypes.TOILET_PAPER,
    label: "Papier toilette explosif",
    description: "Remplit l'air de rouleaux blancs et d'une panique esthétique.",
    hint: "Clic gauche pour lancer du papier toilette.",
    damage: 0,
    splashRadius: 0,
    speed: 250,
    gravity: 900,
    fuseMs: 780,
    cooldownMs: 620,
    color: "#f6f2eb",
    effect: "toilet",
    destructive: false,
  },
  {
    itemType: WeaponTypes.RUBBER_CHICKEN,
    label: "Poulet caoutchouc",
    description: "Un projectile jaune qui fait surtout du bruit et du spectacle.",
    hint: "Clic gauche pour lancer un poulet caoutchouc.",
    damage: 0,
    splashRadius: 0,
    speed: 270,
    gravity: 920,
    fuseMs: 700,
    cooldownMs: 580,
    color: "#ffda4d",
    effect: "chicken",
    destructive: false,
  },
  {
    itemType: WeaponTypes.DISCO_GLOBE,
    label: "Boule disco",
    description: "Fait une explosion de lumière et de paillettes multicolores.",
    hint: "Clic gauche pour lancer une boule disco.",
    damage: 0,
    splashRadius: 0,
    speed: 245,
    gravity: 880,
    fuseMs: 760,
    cooldownMs: 640,
    color: "#8b7bff",
    effect: "disco",
    destructive: false,
  },
];

export function weaponByItem(itemType) {
  return WEAPONS.find((weapon) => weapon.itemType === String(itemType)) || null;
}

export function isWeaponItem(itemType) {
  return Boolean(weaponByItem(itemType));
}
